name: "brew-dependency-submission-action"
version: "1.1.0"

locations:
  - name: "Actions Versions"
    paths:
      - ".github/workflows/*.yml"
      - "*.md"
    patterns:
      # Actions
      - 'advanced-security/brew-dependency-submission-action@v([0-9]\.[0-9]\.[0-9])'
