name: 'brew-dependency-submission-action'
description: 'Brew Lockfile Dependency Submission Action'

inputs:
  brew-lock:
    description: "Brew Lockfile location"

  repository:
    description: Repository Owner and Repository Name
    default: ${{ github.repository }}

  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}

  argvs:
    description: Additional Arguments

runs:
  using: "composite"
  steps:
    # [optional] Make sure your version of Python is installed
    # - uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.10'

    - shell: bash
      run: |
        export PYTHONPATH=${{ github.action_path }}:${{ github.action_path }}/vendor
        python3 -m bldsa \
          --brewlock "${{ inputs.brew-lock }}" \
          --github-token "${{ inputs.token }}" \
          --github-repository "${{ inputs.repository }}" \
          ${{ inputs.argvs }}

