name: Python Action Build & Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    uses: advanced-security/reusable-workflows/.github/workflows/python.yml@v0.2.0
    secrets: inherit

  action-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Run action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
